/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculator;

import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Federico Patricio Jr.
 */
public class AboutActivity extends javax.swing.JFrame {

    /**
     * Creates new form AboutActivity
     */
    public AboutActivity() {
        initComponents();
         back.setToolTipText(null);
         //String version = this.getClass().getPackage().getName();
        //appName.setText(version);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        icon = new javax.swing.JLabel();
        appName = new javax.swing.JLabel();
        version = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        header = new javax.swing.JLabel();
        openSource = new javax.swing.JPanel();
        appLogo = new javax.swing.JLabel();
        developerTitle = new javax.swing.JLabel();
        developerName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        changeLog = new javax.swing.JLabel();
        opensource = new javax.swing.JLabel();
        dScroll = new javax.swing.JScrollPane();
        description = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/ic_launcher.png"))); // NOI18N
        icon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 320, 90));

        appName.setBackground(new java.awt.Color(0, 102, 102));
        appName.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        appName.setForeground(new java.awt.Color(255, 204, 0));
        appName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        appName.setText("Calculator");
        getContentPane().add(appName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 300, -1));

        version.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        version.setForeground(new java.awt.Color(255, 255, 255));
        version.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        version.setText("Version 1.0");
        getContentPane().add(version, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 140, 310, -1));

        back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/ic_back.png"))); // NOI18N
        back.setLabelFor(header);
        back.setToolTipText(""); // NOI18N
        back.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        header.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/math_equations_bg.png"))); // NOI18N
        getContentPane().add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, 180));

        openSource.setBackground(new java.awt.Color(102, 102, 102));
        openSource.setPreferredSize(new java.awt.Dimension(320, 480));
        openSource.setRequestFocusEnabled(false);

        appLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/ic_launcher.png"))); // NOI18N

        developerTitle.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        developerTitle.setForeground(new java.awt.Color(255, 255, 255));
        developerTitle.setText("Developed by");

        developerName.setBackground(new java.awt.Color(255, 255, 255));
        developerName.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        developerName.setForeground(new java.awt.Color(255, 255, 255));
        developerName.setText("Federico Patricio Jr.");
        developerName.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("About");

        changeLog.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        changeLog.setForeground(new java.awt.Color(255, 255, 255));
        changeLog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/ic_changelog.png"))); // NOI18N
        changeLog.setText("Changelogs");
        changeLog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changeLogMouseClicked(evt);
            }
        });

        opensource.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        opensource.setForeground(new java.awt.Color(255, 255, 255));
        opensource.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/ic_code.png"))); // NOI18N
        opensource.setText("Open Source");
        opensource.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                opensourceMouseClicked(evt);
            }
        });

        dScroll.setBorder(null);

        description.setEditable(false);
        description.setBackground(new java.awt.Color(102, 102, 102));
        description.setText("A simple Calculator Functions and  Design using Netbeans\n✅ Addition\n✅ Multiplication\n✅ Subtraction\n✅ Division\n✅ Percentage");
        dScroll.setViewportView(description);

        javax.swing.GroupLayout openSourceLayout = new javax.swing.GroupLayout(openSource);
        openSource.setLayout(openSourceLayout);
        openSourceLayout.setHorizontalGroup(
            openSourceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(openSourceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(openSourceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(openSourceLayout.createSequentialGroup()
                        .addComponent(appLogo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(openSourceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(developerTitle)
                            .addComponent(developerName))
                        .addContainerGap(110, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, openSourceLayout.createSequentialGroup()
                        .addGroup(openSourceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(openSourceLayout.createSequentialGroup()
                                .addComponent(changeLog)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(opensource))
                            .addGroup(openSourceLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(openSourceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18))))
        );
        openSourceLayout.setVerticalGroup(
            openSourceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(openSourceLayout.createSequentialGroup()
                .addContainerGap(159, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(openSourceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(changeLog)
                    .addComponent(opensource))
                .addGap(40, 40, 40)
                .addGroup(openSourceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, openSourceLayout.createSequentialGroup()
                        .addComponent(appLogo)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, openSourceLayout.createSequentialGroup()
                        .addComponent(developerTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(developerName)
                        .addGap(42, 42, 42))))
        );

        getContentPane().add(openSource, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        MainActivity main = new MainActivity();
                main.setVisible(true);
                main.pack();
                main.setLocationRelativeTo(null);
                dispose();
              
    }//GEN-LAST:event_backMouseClicked

    private void changeLogMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changeLogMouseClicked
         ChangeLog info = new ChangeLog();
                info.setVisible(true);
                info.pack();
                info.setLocationRelativeTo(null);
                dispose();
    }//GEN-LAST:event_changeLogMouseClicked

    private void opensourceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opensourceMouseClicked

        Desktop d =Desktop.getDesktop();
        try {
            d.browse(new URI("https://github.com/MasterProvider/Calculator"));
        } catch (URISyntaxException ex) {
            Logger.getLogger(AboutActivity.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(AboutActivity.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_opensourceMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AboutActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AboutActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AboutActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AboutActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AboutActivity().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel appLogo;
    private javax.swing.JLabel appName;
    private javax.swing.JLabel back;
    private javax.swing.JLabel changeLog;
    private javax.swing.JScrollPane dScroll;
    private javax.swing.JTextPane description;
    private javax.swing.JLabel developerName;
    private javax.swing.JLabel developerTitle;
    private javax.swing.JLabel header;
    private javax.swing.JLabel icon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel openSource;
    private javax.swing.JLabel opensource;
    private javax.swing.JLabel version;
    // End of variables declaration//GEN-END:variables
}
