/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculator;

/**
 *
 * @author Federicio Patricio Jr.
 */
public class ChangeLog extends javax.swing.JFrame {

    /**
     * Creates new form ChangeLog
     */
    public ChangeLog() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        positive = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        header = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        dScroll = new javax.swing.JScrollPane();
        description = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        positive.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        positive.setForeground(new java.awt.Color(255, 255, 255));
        positive.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        positive.setText("OK");
        positive.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                positiveMouseClicked(evt);
            }
        });
        jPanel1.add(positive, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 30, 28));

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/ic_launcher.png"))); // NOI18N
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 44, 300, 70));

        header.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/math_equations_bg.png"))); // NOI18N
        jPanel1.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, -1));

        title.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Changelogs");
        jPanel1.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 170, 280, -1));

        dScroll.setBackground(new java.awt.Color(153, 153, 153));
        dScroll.setBorder(null);

        description.setEditable(false);
        description.setBackground(new java.awt.Color(153, 153, 153));
        description.setForeground(new java.awt.Color(51, 51, 51));
        description.setText("This is the first version of Calculator no change yet apply");
        dScroll.setViewportView(description);

        jPanel1.add(dScroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 202, 270, 90));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void positiveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_positiveMouseClicked
        AboutActivity info = new AboutActivity();
                info.setVisible(true);
                info.pack();
                info.setLocationRelativeTo(null);
                dispose();
    }//GEN-LAST:event_positiveMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangeLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangeLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangeLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangeLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangeLog().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane dScroll;
    private javax.swing.JTextPane description;
    private javax.swing.JLabel header;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel positive;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
